name: sup
version: 0.0.4
description: 'A Simple Node Static Server'
main: index.js
bin:
  sup : './bin/sup'
scripts:
  prepublish : "rm bin/sup; yaml2json -sp package.yaml && echo '#!/usr/bin/env node' > bin/sup && coffee -cpb lib/server.coffee >> bin/sup && chmod u+x bin/sup && chmod g+x bin/sup"
  test: 'make test'
repository:
  type: git
  url: 'git://github.com/q3boy/sup.git'
keywords:
  - http
  - static
  - server
author: 'q3boy <q3boy1@gmail.com>'
license: BSD
dependencies:
  argparse: '*'
  connect: '*'
  markdown: '*'
  yamljs: '*'
  jade: '*'
  stylus: '*'
  connect-index: '*'
  connect-compiler: '*'
devDependencies:
  coffee-script: '*'
